apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: traduora-preview
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jeremy.durnell@dallasdstb.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx