version: '3'
services:
  traduora:
    image: traduora/traduora:latest
    container_name: traduora-front
    ports:
     - "8080:8080"
    environment:
      TR_DB_HOST: mysqldb
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:5.7
    container_name: traduora-back
    ports:
     - "3306:3306"
    environment:
      MYSQL_DATABASE: tr_dev
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
